"use client";
import { useState, type CSSProperties, type FormEvent } from "react";
import HomeTrustShowcase from "./HomeTrustShowcase";

type ChatMessage={from:"bot"|"user";text:string};

const services = [
  { n:"01", icon:"software", title:"Mobile App Development", text:"Secure, polished Android, iOS and cross-platform apps designed for real users and built to grow.", tags:["Flutter","Android","iOS"] },
  { n:"02", icon:"software", title:"Web Development", text:"Fast, responsive websites and web applications engineered for performance, trust, conversion and SEO.", tags:["Next.js","Business","E-commerce"] },
  { n:"03", icon:"ai", title:"Google Ads & PPC", text:"Search and performance campaigns built around qualified traffic, conversion tracking and measurable return.", tags:["Google Ads","PPC","Analytics"] },
  { n:"04", icon:"experience", title:"SEO & Search Growth", text:"Technical, on-page and content-led SEO that improves visibility, relevance and long-term organic growth.", tags:["Technical SEO","Content","Local SEO"] },
  { n:"05", icon:"experience", title:"Meta Ads & Social Marketing", text:"Facebook and Instagram campaigns, creative strategy and social growth designed around your business goals.", tags:["Meta Ads","Facebook","Instagram"] },
  { n:"06", icon:"experience", title:"Digital Marketing", text:"Integrated digital marketing across search, social, content and conversion journeys to grow your online presence.", tags:["Strategy","Content","Growth"] },
  { n:"07", icon:"software", title:"Custom Software Development", text:"Purpose-built platforms and systems designed around your workflows instead of forcing you into a template.", tags:["Custom","API","Platforms"] },
  { n:"08", icon:"experience", title:"UI/UX & Product Design", text:"Research-led product design that makes websites, apps and digital services clear, useful and memorable.", tags:["Research","UX","Design"] },
  { n:"09", icon:"ai", title:"Generative AI & Automation", text:"Practical AI assistants, intelligent workflows and automation connected to real business needs.", tags:["GenAI","Agents","Automation"] },
  { n:"10", icon:"cloud", title:"Cloud & DevOps", text:"Reliable cloud architecture, deployments, monitoring and infrastructure that help digital products scale confidently.", tags:["AWS","Azure","DevOps"] },
  { n:"11", icon:"cloud", title:"Cybersecurity", text:"Security reviews, secure architecture and practical protection built into applications and delivery processes.", tags:["Security","Audit","Risk"] },
  { n:"12", icon:"ai", title:"Data Analytics & Insights", text:"Dashboards, reporting and data workflows that turn business information into clearer decisions.", tags:["BI","Data","Forecasting"] },
];
const whyReasons=[
 {n:"01",title:"On-time delivery",text:"We plan realistic milestones, communicate progress clearly and stay focused on shipping dependable work when promised."},
 {n:"02",title:"Affordable, practical pricing",text:"We shape solutions around the value you need and the budget you are working with—without unnecessary complexity."},
 {n:"03",title:"Satisfaction-focused service",text:"We collaborate closely, refine the work with you and remain accountable from first discussion through final delivery."},
 {n:"04",title:"One digital growth partner",text:"Development, design, SEO and paid marketing work together so your product and your growth strategy support each other."},
];
const industries=["Startups","Retail & Commerce","Education","Professional Services","Healthcare","Travel","Real Estate","Local Businesses"];
const stack=[
 {name:"Flutter",mark:"Fl"},{name:"React",mark:"Re"},{name:"Next.js",mark:"N"},{name:"Google Ads",mark:"G"},{name:"Meta Ads",mark:"M"},{name:"Python",mark:"Py"},{name:"TypeScript",mark:"TS"},{name:"SEO",mark:"SEO"},{name:"Firebase",mark:"Fb"},{name:"Supabase",mark:"SB"},{name:"PostgreSQL",mark:"PG"},{name:"Analytics",mark:"GA"},{name:"Node.js",mark:"N."},{name:"Figma",mark:"Fi"}
];
const work=[
 {type:"MOBILE & WEB",title:"Digital products built to earn trust",text:"Modern mobile apps, business websites, e-commerce and web products engineered for speed, usability and conversion.",accent:"violet",metric:"Built to perform"},
 {type:"SEARCH & GROWTH",title:"Visibility that turns into opportunity",text:"SEO, Google Ads and conversion-focused landing experiences designed to help the right customers find and choose you.",accent:"cyan",metric:"Growth focused"},
 {type:"SOCIAL & BRAND",title:"Campaigns built around real business goals",text:"Meta Ads, social marketing and creative digital strategy aligned with awareness, leads, sales and long-term brand growth.",accent:"blue",metric:"Measurable reach"},
];
const Arrow=()=> <span aria-hidden="true">↗</span>;
const ServiceGlyph=({name}:{name:string})=>{
 const common={viewBox:"0 0 32 32","aria-hidden":true};
 if(name==="ai")return <svg {...common}><circle cx="16" cy="16" r="5"/><circle cx="7" cy="9" r="2"/><circle cx="25" cy="8" r="2"/><circle cx="7" cy="24" r="2"/><circle cx="25" cy="24" r="2"/><path d="m10.5 11.7 2.2 1.6m8.8-2.1-2.4 2M10.6 21.2l2.2-1.7m8.5.3 2.1 1.9M16 11V6m0 20v-5"/></svg>;
 if(name==="software")return <svg {...common}><rect x="4" y="6" width="24" height="20" rx="3"/><path d="M4 11h24M9 8.5h.01m4 0h.01M13 16l-3 3 3 3m6-6 3 3-3 3m-1-8-4 10"/></svg>;
 if(name==="cloud")return <svg {...common}><path d="M9 24h14a5 5 0 0 0 .5-10A8 8 0 0 0 8.3 12.1 6 6 0 0 0 9 24Z"/><path d="m13 18 3-3 3 3m-3-3v7"/></svg>;
 if(name==="field")return <svg {...common}><circle cx="16" cy="16" r="11"/><path d="M5 16h22M16 5c3 3 4.5 6.7 4.5 11S19 24 16 27c-3-3-4.5-6.7-4.5-11S13 8 16 5Z"/><circle cx="23.5" cy="9" r="2.5"/></svg>;
 if(name==="enterprise")return <svg {...common}><rect x="5" y="5" width="9" height="9" rx="2"/><rect x="18" y="5" width="9" height="9" rx="2"/><rect x="5" y="18" width="9" height="9" rx="2"/><rect x="18" y="18" width="9" height="9" rx="2"/><path d="M14 9.5h4M9.5 14v4m13-4v4M14 22.5h4"/></svg>;
 return <svg {...common}><path d="M7 25 9.5 17 21 5.5a2.1 2.1 0 0 1 3 3L12.5 20 7 25Z"/><path d="m18.5 8 5 5M9.5 17l3 3M6 8h5M8.5 5.5v5M23 20h4m-2-2v4"/></svg>;
};
const getServixaReply=(question:string)=>{
 const q=question.toLowerCase();
 if(/agent|human|person|representative|consultant|counsel|team member|someone/.test(q)) return "Yes—our team would be happy to speak with you. Choose WhatsApp for a quick consultation, email us, or send your project details through the inquiry form below.";
 if(/price|cost|budget|quote|kitna|charges/.test(q)) return "Servixa offers practical, affordable pricing based on your goals, features and timeline. Share the project basics and our team can prepare a suitable proposal.";
 if(/time|timeline|duration|days|weeks|kab/.test(q)) return "On-time delivery is a core Servixa commitment. We confirm a realistic milestone plan after understanding the scope and keep progress visible throughout the project.";
 if(/google ads|ppc|adwords/.test(q)) return "Servixa provides Google Ads and PPC services including campaign setup, keyword planning, conversion tracking, landing-page alignment and ongoing optimization.";
 if(/seo|search engine|ranking|google rank/.test(q)) return "Servixa provides technical SEO, on-page SEO, local SEO, content optimization and search-growth strategy for websites that need stronger organic visibility.";
 if(/meta|facebook|instagram|social media|marketing/.test(q)) return "Servixa supports Meta Ads, Facebook and Instagram campaigns, social marketing, campaign strategy and digital growth planning.";
 if(/ai|automation|machine learning|chatbot/.test(q)) return "Servixa builds practical AI solutions including business automation, intelligent assistants, data-driven products and custom AI integrations.";
 if(/mobile|android|ios|app/.test(q)) return "Yes. Mobile app development is one of Servixa’s core services, including Android, iOS and cross-platform Flutter applications.";
 if(/web|website|ecommerce|saas/.test(q)) return "Web development is a core Servixa service. We build business websites, web apps, e-commerce experiences and scalable SaaS products with strong performance and SEO foundations.";
 if(/contact|email|whatsapp|call|meeting/.test(q)) return "Contact Servixa at servixaa@gmail.com, use the WhatsApp button, or send the project form on this page. The team will respond directly.";
 if(/service|what do you do|kya kr|offer/.test(q)) return "Servixa specializes in mobile app development, web development, Google Ads, SEO, Meta Ads, digital marketing, UI/UX, custom software and practical AI solutions.";
 if(/hello|hi|hey|salam|assalam/.test(q)) return "Hello! I’m the Servixa Assistant. I can guide you about our development, SEO, advertising and digital marketing services, timelines and the best way to start.";
 return "Servixa helps businesses build and grow online through mobile apps, websites, Google Ads, Meta Ads, SEO, digital marketing and custom software. Tell me what you need and I’ll guide you.";
};

export default function Home(){
 const [menuOpen,setMenuOpen]=useState(false); const [sent,setSent]=useState(false); const [sending,setSending]=useState(false); const [submitError,setSubmitError]=useState("");
 const [servicesExpanded,setServicesExpanded]=useState(false);
 const [chatOpen,setChatOpen]=useState(false); const [chatInput,setChatInput]=useState("");
 const [chatMessages,setChatMessages]=useState<ChatMessage[]>([{from:"bot",text:"Hi! I’m the Servixa Assistant. Tell me what you want to build or grow, and I’ll guide you to the right service."}]);
 const askBot=(question:string)=>{const clean=question.trim();if(!clean)return;setChatMessages(m=>[...m,{from:"user",text:clean},{from:"bot",text:getServixaReply(clean)}]);setChatInput("");};
 const handleChat=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();askBot(chatInput)};
 const handleInquiry=async(e:FormEvent<HTMLFormElement>)=>{
  e.preventDefault();
  setSending(true); setSubmitError("");
  const form=e.currentTarget;
  const data=new FormData(form);
  data.append("_subject",`New Servixa inquiry: ${data.get("service")||"Project request"}`);
  data.append("_template","table");
  data.append("_captcha","false");
  data.append("_autoresponse","Thank you for contacting Servixa. We have received your inquiry and our team will respond shortly.");
  try{
   const response=await fetch("https://formsubmit.co/ajax/servixaa@gmail.com",{method:"POST",headers:{Accept:"application/json"},body:data});
   const result=await response.json();
   if(!response.ok||result.success===false) throw new Error(result.message||"Submission failed");
   form.reset(); setSent(true);
  }catch{
   setSubmitError("Message send nahi ho saka. Please dobara try karein ya servixaa@gmail.com par email karein.");
  }finally{setSending(false)}
 };
 return <main>
  <nav className="nav shell" aria-label="Primary navigation">
   <a className="brand" href="#top" aria-label="Servixa home"><img className="brand-logo" src="/servixa-logo.webp" alt="Servixa"/></a>
   <button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle menu"><span/><span/></button>
   <div className={`nav-links ${menuOpen?"open":""}`}><a href="#services" onClick={()=>setMenuOpen(false)}>Services</a><a href="#work" onClick={()=>setMenuOpen(false)}>Work</a><a href="#industries" onClick={()=>setMenuOpen(false)}>Industries</a><a href="#about" onClick={()=>setMenuOpen(false)}>About</a><a href="#contact" onClick={()=>setMenuOpen(false)}>Contact</a></div>
   <a className="nav-cta" href="#contact">Start a project <Arrow/></a>
  </nav>
  <header id="top" className="hero shell">
   <div className="hero-glow"/><div className="eyebrow"><span/> 100+ projects · 5.0/5 rating · 4+ years experience</div>
   <h1>Build better.<br/><em>Grow faster.</em></h1>
   <div className="hero-bottom"><p>Servixa builds mobile apps and websites, then helps businesses grow through Google Ads, Meta Ads, SEO and digital marketing—with affordable pricing, on-time delivery and satisfaction-focused service.</p><div className="hero-actions"><a className="button primary" href="#contact">Discuss your project <Arrow/></a><a className="button ghost" href="#services">Explore our services ↓</a></div></div>
   <div className="word-scene" aria-hidden="true"><div className="word-glow"/><div className="servixa-word">{"SERVIXA".split("").map((letter,i)=><span style={{"--letter":i} as CSSProperties} key={letter+i}>{letter}</span>)}</div><p>Apps · Web · Google Ads · SEO · Marketing</p><i className="word-line"/></div>
  </header>
  <section className="proof-strip"><div className="shell"><p>Development + digital growth in one team</p><div><span>On-time delivery</span><i/> <span>Affordable pricing</span><i/> <span>100% satisfaction focus</span><i/> <span>5.0/5 rating</span></div></div></section>
  <HomeTrustShowcase/>
  <section className="ticker" aria-label="Servixa capabilities"><div>MOBILE APPS <span>✦</span> WEB DEVELOPMENT <span>✦</span> GOOGLE ADS <span>✦</span> SEO <span>✦</span> META ADS <span>✦</span> DIGITAL MARKETING</div></section>
  <section id="services" className="section shell">
   <div className="section-head"><div><p className="kicker">Capabilities</p><h2>Build your product.<br/><span>Grow your business.</span></h2></div><p>Servixa brings development, design, search and paid marketing together—starting with the services businesses need most to launch, improve and grow online.</p></div>
   <div id="servixa-services-grid" className={`services-grid ${servicesExpanded?"expanded":""}`}>{services.slice(0,servicesExpanded?services.length:4).map((s,i)=><article className="service-card" key={s.n}><div className={`service-art art-${i}`}><div className="service-top"><span>{s.n}</span><Arrow/></div><h3>{s.title}</h3><span className="art-grid" aria-hidden="true"/><span className="art-orbit" aria-hidden="true"><i/><i/></span><span className="art-panel" aria-hidden="true"><b/><b/><b/></span><div className="service-icon" aria-hidden="true"><ServiceGlyph name={s.icon}/></div></div><div className="service-body"><p>{s.text}</p><div className="tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div><a className="service-link" href="#contact">Discuss this service <Arrow/></a></div></article>)}</div>
   <div className="services-expand"><p>{servicesExpanded?`Showing all ${services.length} core capabilities.`:"Explore the complete Servixa service portfolio."}</p><button type="button" onClick={()=>setServicesExpanded(v=>!v)} aria-expanded={servicesExpanded} aria-controls="servixa-services-grid">{servicesExpanded?"Show fewer services":`View all ${services.length} services`} <span aria-hidden="true">{servicesExpanded?"↑":"↓"}</span></button></div>
  </section>
  <section className="why-section"><div className="shell"><div className="why-heading"><div><p className="kicker light">Why choose Servixa</p><h2>Professional delivery.<br/><span>Personal accountability.</span></h2></div><p>Clients choose Servixa for practical pricing, dependable delivery and one team that can build the product and support its digital growth.</p></div><div className="why-grid">{whyReasons.map((reason,i)=><article key={reason.n}><div className="why-orbit" aria-hidden="true"><span>{reason.n}</span><i style={{"--why-index":i} as CSSProperties}/></div><h3>{reason.title}</h3><p>{reason.text}</p></article>)}</div><div className="why-footer"><span><i/> Ready when your ambition is</span><a className="button primary" href="#contact">Start a conversation <Arrow/></a></div></div></section>
  <section id="work" className="work-section"><div className="shell">
   <div className="section-head"><div><p className="kicker light">Development + growth</p><h2>Digital work made<br/><span>useful.</span></h2></div><p>We combine strong product execution with the marketing channels that help people discover, trust and choose your business.</p></div>
   <div className="work-grid">{work.map((item,i)=><article className={`work-card ${item.accent}`} key={item.type}><div className="work-visual"><span className="work-number">0{i+1}</span><div className={`work-hologram holo-${i}`} aria-hidden="true"><span className="holo-ring ring-a"/><span className="holo-ring ring-b"/><span className="holo-ring ring-c"/><i className="holo-node node-a"/><i className="holo-node node-b"/><i className="holo-node node-c"/><div className="work-symbol"><ServiceGlyph name={i===0?"software":"experience"}/></div><div className="holo-bars"><b/><b/><b/><b/></div></div><small>{item.metric}</small></div><div className="work-copy"><span>{item.type}</span><h3>{item.title}</h3><p>{item.text}</p><a href="#contact">Explore a project with us <Arrow/></a></div></article>)}</div>
  </div></section>
  <section id="about" className="dark-section"><div className="shell split">
   <div className="signal-panel brand-panel"><div className="brand-mesh" aria-hidden="true"/><div className="brand-scan" aria-hidden="true"/><div className="brand-stage"><span className="brand-overline">About Servixa</span><div className="panel-word" aria-label="Servixa">{"SERVIXA".split("").map((letter,i)=><span key={letter+i} style={{"--panel-letter":i} as CSSProperties}>{letter}</span>)}</div><p>Build. Launch. Grow.</p><div className="panel-capabilities"><span>Mobile Apps</span><span>Web</span><span>SEO</span><span>Ads</span></div></div><div className="status"><i/> Ready to build <b>Let&apos;s talk ↗</b></div></div>
   <div className="split-copy"><p className="kicker light">About Servixa</p><h2>We build digital products<br/><span>and help them grow.</span></h2><p>Servixa specializes in mobile app development, web development, Google Ads, Meta Ads, SEO, digital marketing, UI/UX and custom software. With 4+ years of experience and more than 100 projects completed, we focus on delivering professional work on time, at practical pricing, with a 5/5 service standard.</p><p>We serve clients in Kot Addu, Islamabad, Lahore and Multan, and work with businesses across New Zealand, Dubai, Australia and Germany.</p><div className="metric-row"><div><strong>4+</strong><span>Years experience</span></div><div><strong>100+</strong><span>Projects delivered</span></div><div><strong>5/5</strong><span>Client rating</span></div></div></div>
  </div></section>
  <section id="industries" className="section shell industries"><div className="section-head compact"><div><p className="kicker">Industries</p><h2>Built for your<br/><span>world.</span></h2></div><p>Development and digital growth services adapted to your customers, market and business goals.</p></div><div className="industry-list">{industries.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong><Arrow/></div>)}</div></section>
  <section className="process-section"><div className="shell"><p className="kicker">How we deliver</p><h2>Clarity at every step.</h2><div className="process">{[["01","Discover","We understand your goals, customers, scope, budget and the clearest path to value."],["02","Plan & Design","We shape the experience, technical approach and delivery roadmap before execution."],["03","Build & Launch","We develop, test and launch in visible milestones with clear communication."],["04","Grow & Improve","We support SEO, advertising, analytics and ongoing improvements after launch."]].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="tech-section"><div className="shell tech-heading"><p className="tech-badge"><i/> Tools & platforms</p><h2>Built and grown with <em>proven</em> technologies.</h2><p>We use modern development frameworks together with search, advertising, analytics and design tools to support the full digital journey.</p></div><div className="tech-marquee" aria-label="Servixa technology stack"><div className="tech-track">{[...stack,...stack].map((tech,i)=><article className={`tech-card tech-${i%7}`} key={`${tech.name}-${i}`} aria-hidden={i>=stack.length}><div className="tech-mark">{tech.mark}</div><strong>{tech.name}</strong></article>)}</div></div></section>
  <section id="contact" className="contact-section"><div className="shell contact-grid"><div><p className="kicker light">Start a conversation</p><h2>Ready to build or grow?<br/><span>Let&apos;s make it happen.</span></h2><p>Tell us what you need—mobile app, website, Google Ads, SEO, Meta Ads, marketing or custom software. We&apos;ll help define a practical next step.</p><div className="business-mails"><a href="mailto:servixaa@gmail.com?subject=General%20Servixa%20inquiry"><small>General</small><strong>info@servixa.com</strong><Arrow/></a><a href="mailto:servixaa@gmail.com?subject=Servixa%20sales%20inquiry"><small>Sales</small><strong>sales@servixa.com</strong><Arrow/></a><a href="mailto:servixaa@gmail.com?subject=Servixa%20support%20request"><small>Support</small><strong>support@servixa.com</strong><Arrow/></a><a href="mailto:servixaa@gmail.com?subject=Servixa%20career%20inquiry"><small>Careers</small><strong>careers@servixa.com</strong><Arrow/></a></div></div>
  {sent?<div className="success"><div>✓</div><h3>Message sent.</h3><p>Your inquiry has been delivered directly to Servixa. Our team will reply to your email.</p><button onClick={()=>setSent(false)}>Send another</button></div>:<form onSubmit={handleInquiry}><label>Name<input required name="name" placeholder="Your name"/></label><label>Work email<input required type="email" name="email" placeholder="you@company.com"/></label><label>Company<input name="company" placeholder="Company name"/></label><label>What do you need?<select name="service" defaultValue=""><option value="" disabled>Select a service</option>{services.map(s=><option key={s.n}>{s.title}</option>)}</select></label><label className="full">Project details<textarea required name="details" placeholder="Tell us a little about your goals..." rows={4}/></label>{submitError&&<p className="form-error full" role="alert">{submitError}</p>}<button className="button primary full" type="submit" disabled={sending}>{sending?"Sending...":"Send message"} {!sending&&<Arrow/>}</button></form>}</div></section>
  <aside className={`chatbot ${chatOpen?"open":""}`} aria-label="Servixa company assistant">
   {chatOpen&&<div className="chat-window"><header><div className="chat-avatar"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5.75h14a2 2 0 0 1 2 2v7.5a2 2 0 0 1-2 2h-7.2L7 20.5v-3.25H5a2 2 0 0 1-2-2v-7.5a2 2 0 0 1 2-2Z"/><circle cx="8" cy="11.5" r="1"/><circle cx="12" cy="11.5" r="1"/><circle cx="16" cy="11.5" r="1"/></svg></div><div><strong>Servixa Assistant</strong><span><i/> Online · Company guidance</span></div><button onClick={()=>setChatOpen(false)} aria-label="Close Servixa Assistant">×</button></header><div className="chat-messages" aria-live="polite">{chatMessages.map((m,i)=><p className={m.from} key={`${m.from}-${i}`}>{m.text}</p>)}</div>{chatMessages.length<3&&<div className="chat-suggestions"><button onClick={()=>askBot("What services do you offer?")}>Explore services</button><button onClick={()=>askBot("Can you build my website or app?")}>Plan a project</button><button onClick={()=>askBot("Can you help with SEO and ads?")}>Grow my business</button></div>}<div className="chat-handoff"><a className="handoff-whatsapp" href="https://wa.me/923078155793?text=Hello%20Servixa%2C%20I%20would%20like%20a%20project%20consultation." target="_blank" rel="noreferrer">WhatsApp consultation <Arrow/></a><a href="mailto:servixaa@gmail.com?subject=Servixa%20project%20consultation">Email our team <Arrow/></a></div><a className="chat-contact" href="#contact" onClick={()=>setChatOpen(false)}>Send project details <Arrow/></a><form onSubmit={handleChat}><label className="sr-only" htmlFor="servixa-chat">Ask Servixa</label><input id="servixa-chat" value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="How can Servixa help?" autoComplete="off"/><button type="submit" aria-label="Send question">↑</button></form><small>Servixa service guidance · No personal data required</small></div>}
   <button className="chat-launcher" onClick={()=>setChatOpen(!chatOpen)} aria-expanded={chatOpen} aria-label={chatOpen?"Close Servixa Assistant":"Open Servixa Assistant"}><span>{chatOpen?"×":<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5.75h14a2 2 0 0 1 2 2v7.5a2 2 0 0 1-2 2h-7.2L7 20.5v-3.25H5a2 2 0 0 1-2-2v-7.5a2 2 0 0 1 2-2Z"/><circle cx="8" cy="11.5" r="1"/><circle cx="12" cy="11.5" r="1"/><circle cx="16" cy="11.5" r="1"/></svg>}</span><b>{chatOpen?"Close":"Ask Servixa"}</b></button>
  </aside>
  <a className="whatsapp-float" href="https://wa.me/923078155793?text=Hello%20Servixa%2C%20I%20would%20like%20to%20discuss%20a%20project." target="_blank" rel="noreferrer" aria-label="Chat with Servixa on WhatsApp" title="Chat with Servixa on WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16.04 3C9.39 3 4 8.28 4 14.8c0 2.08.55 4.11 1.6 5.89L4 26.5l6.03-1.54a12.2 12.2 0 0 0 6 1.53h.01c6.64 0 12.04-5.29 12.04-11.79C28.08 8.19 22.68 3 16.04 3Zm7.08 16.66c-.3.83-1.75 1.59-2.44 1.68-.63.08-1.43.12-2.31-.15-.53-.16-1.22-.39-2.1-.76-3.69-1.56-6.1-5.18-6.28-5.42-.18-.24-1.5-1.96-1.5-3.74 0-1.79.95-2.66 1.29-3.02.33-.36.73-.45.97-.45h.7c.22 0 .52-.08.82.62.3.71 1.02 2.46 1.11 2.64.09.18.15.39.03.63-.12.24-.18.39-.36.6-.18.21-.38.47-.54.63-.18.18-.37.37-.16.73.21.36.93 1.5 2 2.43 1.37 1.2 2.53 1.57 2.89 1.75.36.18.57.15.78-.09.21-.24.9-1.03 1.14-1.39.24-.36.48-.3.81-.18.33.12 2.1.97 2.46 1.15.36.18.6.27.69.42.09.15.09.86-.21 1.69Z"/></svg></a>
  <footer className="footer shell"><div className="footer-brand"><div className="brand"><img className="brand-logo" src="/servixa-logo.webp" alt="Servixa"/></div><div className="footer-socials" aria-label="Servixa social media">
   <a href="https://www.instagram.com/servixatech?igsh=NjJmbWp2NTR0ZDM2&amp;igsi=NjJmbWp2NTR0ZDM2" target="_blank" rel="noopener noreferrer" aria-label="Follow Servixa Tech on Instagram" title="Instagram · @servixatech"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.2"/><circle className="icon-dot" cx="17.4" cy="6.7" r="1"/></svg></a>
   <a href="https://www.linkedin.com/company/servixa-digital-solutions/" target="_blank" rel="noopener noreferrer" aria-label="Connect with Servixa Digital Solutions on LinkedIn" title="LinkedIn · Servixa Digital Solutions"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="M8 10v7m0-10v.01M12 17v-4.1c0-1.8 1.2-3 2.8-3s2.7 1.1 2.7 3V17M12 10v7"/></svg></a>
  </div></div><p>Build better. Grow faster.</p><div className="footer-links"><a href="#services">Services</a><a href="#industries">Industries</a><a href="#contact">Contact</a></div><small>© {new Date().getFullYear()} Servixa. All rights reserved.</small></footer>
 </main>;
}
